### ISSUE TITLE
model classes wat beperkt

### ISSUE THREAD

**Issue by stgm** [CodingMuziekwijk/csgo-shadow#2]
Ik denk dat je nog wel wat meer functionaliteit in model classes kunt krijgen (denk aan het interpreteren van de kaart enz)

close deze issue als je het begrepen/gefixt hebt

**Comment by CodingMuziekwijk** [comment]
Bedankt voor de feedback! De extra classes heb ik inderdaad overwogen en zal ik maken. Momenteel ben ik nog aan het orienteren wat er mogelijk is en wat daarvan het slimst is om te doen. De andere twee issues los ik vandaag op. (Heb gisteravond me git repo weer eens kapot gemaakt...)
